ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Ejes estratégicos

Para desarrollar la *Estrategia del uso responsable y ético de datos*, se han establecido los siguientes ejes de actuación, que ampliamos a continuación, junto con las acciones y los proyectos emblemáticos que están asociados.

Por otra parte, de forma general, la Estrategia pivotará sobre los siguientes principios básicos, que fundamentan los ejes estratégicos descritos en esta sección:

* La soberanía de los datos
* Los datos abiertos y la transparencia
* El intercambio de datos y la reutilización
* Una toma de decisiones políticas informada en los datos
* El ciclo de vida de los datos y el acceso continuado o permanente

== El despliegue de la nueva gobernanza de los datos

=== Políticas y procesos de gobernanza

Como apoyo para la finalidad y las funciones de las gerencias y los entes municipales, y en coordinación con las personas responsables y las encargadas de los datos, se deberán definir, poner en práctica y mantener los procesos, los estándares y las políticas municipales que serán aplicables a todos los recursos de datos de la entidad.

Los entes dependientes municipales deberán obtenerlo del CTID en coordinación con las mesas de gobernanza donde se definirán los procesos y las políticas con suficiente detalle para gestionar los recursos de datos de la forma apropiada.
Como mínimo, estos procesos y políticas deberán requerir que se evalúen las inversiones y los proyectos en desarrollo para determinar la aplicabilidad de la metodología ágil, los estándares de datos y contenidos abiertos, la privacidad, y los impactos éticos y sociales. y los indicadores para medir el coste, el uso y la evaluación general en el conjunto de los recursos de datos.
Se debe asegurar que:

* Hay una política de revisión única en cada entidad para realizar las evaluaciones de las inversiones, los análisis de las operaciones o los otros sistemas de evaluación de los recursos de TI, incluidos los proyectos en desarrollo y las actividades en curso.
* Las necesidades de información y los datos se gestionan siguiendo las políticas de gobernanza de la entidad, donde se establecen claramente las funciones, las responsabilidades y los procesos a partir de los cuales el personal de la entidad trata los datos como un activo, así como las relaciones entre tecnología, datos, programas de la entidad, estrategias, requerimientos legales y misión y objetivos operativos.
* Los sistemas de información obsoletos se reemplazan tan rápidamente como sea posible y la planificación presupuestaría incluye las partidas correspondientes de depreciación.

=== Liderazgo y recursos humanos


Los entes dependientes municipales deberán desarrollar un conjunto de requerimientos y capacidades con respecto a los equipos responsables o encargados de los datos, en los cuales se incluirán aspectos sobre acceso, análisis, privacidad y seguridad, entre otros.
Especialmente, es necesario asegurar que los equipos con responsabilidad sobre los datos podrán prever la innovación y adaptarse a ella, en un contexto de cambio constante.
El departamento de Recursos Humanos debe asegurar que el personal ejecutivo/directivo que trata los datos tiene los conocimientos suficientes para ejecutar su tarea de una forma apropiada.
Las personas responsables de las entidades deberán supervisar cómo lleva a cabo sus funciones el personal que trate con los datos, así como coordinarse con el CTID y el o la CDO para seleccionarlo.

=== Privacidad

En cumplimiento del Reglamento 2106/679 de la Unión Europea, el Ayuntamiento designará un delegado o delegada de protección de datos (DPD) corporativa con las funciones que este reglamento le asigna.

Los entes dependientes municipales deben establecer y mantener un programa de protección de datos, conforme a la política municipal de privacidad, que asegure el cumplimiento de los requerimientos de privacidad y desarrolle, evalúe y gestione los riesgos sobre la privacidad.
Cuando se valoran los riesgos de privacidad, los sistemas de privacidad deben considerar los riesgos sobre las personas asociados a la creación, la recogida, el uso, el tratamiento, el almacenaje, el mantenimiento, la difusión o la destrucción de los datos personales.

De acuerdo con la política municipal y la ley, las entidades y los entes municipales solo podrán crear, recoger, usar, almacenar o difundir datos de carácter personal si tienen la autorización pertinente.
Es necesario que se identifique claramente esta autoridad en sus DMS y en el documento de arquitectura (DA).
Los entes deben designar un RDAD y un delegado o delegada de protección de datos con responsabilidad sobre sus datos y que deben responder del desarrollo, la puesta en práctica y el mantenimiento de los programas de privacidad para asegurar el cumplimiento de todas las regulaciones, las normas y las directivas que actúan sobre el ciclo de vida de los datos de carácter personal, mediante una política de privacidad que aplique las medidas legales sobre los riesgos de privacidad.
El CTID, junto con los responsables corporativos de los datos, el o la CDO y el o la DPD, tendrá autoridad sobre la actividad de los subDPD de cada entidad y los coordinarán.

Se deben respetar los principios de protección de datos de carácter personal, los detalles de los cuales se deben establecer bajo la responsabilidad del o de la DPD.
En particular, se incluirán:

* Evaluaciones de impacto.
Las unidades harán evaluaciones de impacto de protección de datos orientadas a asegurar preventivamente que, cuando las operaciones de tratamiento pueden comportar riesgos especialmente relevantes, se tomen las medidas necesarias para reducir, en la medida de lo posible, el riesgo de perjudicar a las personas o afectar negativamente sus derechos y libertades al impedir o limitar su ejercicio o contenido.

* Privacidad por diseño / PET.
Se deben tomar las medidas necesarias para incorporar estrategias de privacidad por diseño o tecnologías de mejora de la privacidad (PET, por las siglas en inglés), a partir de las cuales se tenga en cuenta la salvaguardia de la privacidad de las personas interesadas en todos los procesos de diseño, desarrollo y gestión de los sistemas de datos del Ayuntamiento.
Siempre que sea aplicable, hay que usar algoritmos de encriptación, anonimización o pseudoanonimización.

=== Seguridad de los datos

Para garantizar un nivel adecuado de seguridad de los datos y para asegurar su confidencialidad y uso correcto, el CTID debe designar, para cada unidad o ente, a una persona responsable de la seguridad de los datos o DSO (_data security officer_) responsable del desarrollo y el mantenimiento de un programa de seguridad de los datos en la unidad, de acuerdo con la legislación pertinente y en colaboración con la Comisión Técnica de Seguridad en Protección de Datos.

Los datos estarán protegidos de acuerdo con el riesgo que se derivaría del acceso no autorizado, el uso, la divulgación, la interrupción, la modificación o la destrucción de esta información.
Las unidades deben elaborar un plan de recuperación que incluya las estrategias de continuidad para asegurar que los servicios y el acceso se puedan restaurar a tiempo para satisfacer las necesidades de la misión.
Además, cualquier proyecto o sistema de información deberá garantizar la posibilidad de trazar el acceso a los datos y el análisis de los algoritmos de toma de decisión (o de apoyo a la toma de decisión) y capacitar y facilitar las auditorías que se quieran realizar.
Cualquiera tercero implicado en el tratamiento de datos municipales deberá ofrecer garantías suficientes sobre la implantación y el mantenimiento de las medidas de seguridad requeridas, y las otras directrices que define el xref:{lang}/tech-practices:ROOT:aim-and-scope.adoc[Código de prácticas tecnológicas] y la Comisión Técnica de Seguridad.

Todos los proyectos y los sistemas deben cumplir con las leyes y los reglamentos existentes, incluidos, entre otros, el Reglamento general de protección de datos, la Ley española de protección de datos, el Decreto 3/2010, de 8 de enero, que regula el Esquema Nacional de Seguridad en el Ámbito de la Administración Electrónica, y las normas internacionales con respecto a seguridad, en particular la norma ISO/IEC 27002:2005, que establece directrices y principios generales para iniciar, poner en práctica, mantener y mejorar la gestión de la seguridad de la información en una organización.

La seguridad física o lógica de los datos estará determinada por los estándares definidos por el IMI.

=== Colaboración Coordinación y Supervisión

La gobernanza general de los datos se describe en la Instrucción que acompaña esta medida en el anexo 10.1.
Se constituye la Coordinación Transversal de Datos, el objetivo principal de la cual es coordinar proyectos transversales y, al mismo tiempo, actuar como mecanismo de difusión de proyectos.

Para una coordinación correcta entre los ámbitos de gestión municipales, se definirán personas responsables sectoriales de datos que tendrán como responsabilidad los datos de su propia gerencia y la coordinación en el conjunto de la corporación.
A partir de la coordinación transversal de los datos, se podrá realizar el seguimiento y el establecimiento de directrices sobre los trabajos llevados a cabo tanto en la OMD como en los diferentes centros sectoriales de almacén, análisis y difusión de datos municipales; el establecimiento de los criterios operativos y los criterios de cuidado para garantizar todos los aspectos del ciclo de vida y añadir valor a los datos; el seguimiento de proyectos transversales y corporativos, así como la gestión de la protección de datos o la normativa de protección intelectual y autoría de los datos.

Esta coordinación debe propiciar una gestión y una revisión correctas de los recursos y los programas, y asegurar una gestión del presupuesto coordinada y unificada, en la cual también participará, para la revisión y la autorización el o la CDO con la voluntad de proporcionar una dirección corporativa efectiva, específica y visible de los recursos de TI y de los datos.

Igualmente, las gerencias de cada unidad, en consulta con los responsables municipales de datos, deberán describir los procesos a partir de los cuales se definirá el inventario de los recursos de TI para alcanzar los objetivos de gestión de una forma eficiente, ponderando las nuevas inversiones de TI y sus potencialidades y adecuación al inventario corporativo.
También será necesario que se identifiquen las diferencias entre el presupuesto programado y el ejecutado, los calendarios y la evaluación de los objetivos de TI, y que se lleven a cabo las medidas correctivas necesarias.

== La gestión ética y responsable de los datos

Este eje establece los principios y las directrices para gestionar correctamente los datos, de acuerdo con los principios indicados en esta medida.
Los aspectos más técnicos de esta gestión se incorporan en el xref:{lang}/tech-practices:ROOT:aim-and-scope.adoc[Código de prácticas tecnológicas], publicado bajo la Medida de gobierno para la digitalización abierta: _software libre_ y desarrollo ágil de servicios, de octubre del 2017.

SLos entes dependientes municipales deberán gestionar los datos de una forma responsable, inventariar y registrar los procesos de tratamiento autorizados, identificar las fuentes de los datos y sus metadatos básicos, garantizarles un ciclo de vida correcto, y tener en cuenta a las personas usuarias en el momento de determinar su formato o frecuencia de actualización, entre otras consideraciones de la gestión de datos.
Deben colaborar con las otras entidades en la promoción de unos servicios públicos eficientes para cumplir con todas las políticas de transparencia y las que tienen relación con la privacidad, la seguridad y la accesibilidad.

Específicamente, los entes deben seguir todos los procesos establecidos por el o por la DPD con respecto al cumplimiento riguroso de la normativa de protección de datos, notificar a la Autoridad Catalana de Protección de Datos la creación de bases de datos cuando sea necesario, y nombrar a las personas responsables y encargadas de los datos.
Se deberá minimizar la recogida de datos personales, aplicar la anonimización o pseudoanonimización siempre que sea posible, obtener el consentimiento de las personas interesadas, y tener en cuenta la repercusión de cada acción en cada uno de los momentos del ciclo de vida de los datos sobre cada uno de los otros momentos o personas interesadas.

=== Principios rectores de la gestión ética y responsable de los datos

Los entes dependientes municipales deberán incorporar los siguientes pasos en la planificación, la presupuestación y la gestión, cuando sea adecuado:

* Los datos municipales deben ser gestionados éticamente durante su ciclo de vida (creación, recogida, almacenaje, uso, análisis, difusión, archivo y destrucción).
* La información municipal se gestiona como bien común y se hace posible su acceso, consulta y uso al público a partir de las disposiciones legales vigentes.
* Se debe registrar la actividad llevada a cabo sobre los datos en un conjunto amplio de metainformación, siguiendo los esquemas de metadatos más adecuados para las explotaciones de cada negocio.
* Se deben identificar los riesgos contra la privacidad o de seguridad durante todo el ciclo vida de los datos y elaborar análisis de riesgos y soluciones de seguridad.
* Se debe gestionar mediante uno asignación clara de funciones y responsabilidades para promover un diseño y una operación eficientes de todos los procesos de gestión.

Los entes tienen la responsabilidad de proporcionar la información al público de una forma coherente con sus objetivos y misión y a partir de la legislación vigente.
Deberán proporcionar datos anonimizados, de forma que se pueda promover el acceso, el análisis y la reutilización para un conjunto amplio de propósitos.
Será necesario que la información sea accesible públicamente y automatizable y que esté descrita correctamente, completa y actualizada.
Eso incluye también que los datos estén disponibles en formatos accesibles a personas con diversidad funcional.
Es necesario considerar los costes de este servicio público para la entidad, ya que habría que evitar establecer tasas o precios públicos.

Los entes deben almacenar la información de manera que se permita la interoperabilidad entre los sistemas de información y, siempre que sea adecuado, su difusión pública mediante el uso de formatos abiertos, estándares de datos y metadatos.
Las entidades también deben poner a disposición del público mecanismos para obtener una retroacción en relación con los datos.

Los sistemas de financiación municipales deben poder premiar las unidades que incluyan, en sus contratos de servicios, sistemas de preservación a largo plazo de los datos propios y de su acceso.

El Ayuntamiento y todas las unidades del grupo municipal deberán observar un conjunto de procedimientos orientados a mejorar la adquisición de los datos y que posibiliten una gestión de los datos efectiva, económica, segura, ética, abierta y que garantice la privacidad.
La planificación se debe centrar en los datos que soportan la misión de cada unidad, y se deben implantar procesos de gestión que se integren en la programación y la ejecución presupuestaria.

=== Planificación y presupuesto

La planificación presupuestaria es uno de los puntos esenciales de la elaboración y el mantenimiento de una estrategia de gestión de los datos, y debe permitir asegurar una colaboración efectiva entre las gerencias y las direcciones en este ámbito de gestión.

Planificación estratégica: los planes de gestión de datos (PGD).
Como apoyo a las necesidades de gestión y a la misión del Ayuntamiento de Barcelona, y como aparte de la estrategia general y de la planificación de mejora de procesos del grupo municipal, cada unidad debe elaborar y mantener su propio plan de gestión de los datos (PGD) que describe los objetivos de los recursos de TI, incluidos, entre otros, los procesos descritos en esta estrategia.
El PGD deberá mostrar cómo se relaciona el mapa de los objetivos de los recursos de TI con la misión y las prioridades de la unidad.
Es necesario que los objetivos sean específicos, mensurables y verificables, de manera que se pueda monitorizar su progreso.

Un ejemplo de proyecto emblemático en el área de presupuesto es Presupuesto Abierto, una herramienta para facilitar el análisis y la comprensión de los presupuestos del Ayuntamiento de Barcelona para la ciudadanía.
El proyecto permite descargar datos en formatos abiertos, navegar desde los datos presupuestarios más agregados hasta el máximo nivel de detalle, tanto para el ejercicio actual como para los últimos ejercicios.

=== Inventario

Las unidades deberán mantener un inventario footnote:[_El inventario de cada unidad se integrará a un inventario general del grupo municipal_] de los sistemas de información principales, de sus contenedores y de las herramientas de divulgación con el nivel de detalle que se determine para supervisarlos y gestionarlos.
En este inventario habrá que identificar los conjuntos de datos con información de carácter personal y se determinarán unos procedimientos para permitir revisar regularmente que estos datos tienen la calidad necesaria, que se puede dar respuesta a los derechos de las personas interesadas y que son los mínimos imprescindibles para desarrollar las competencias y las funciones de la unidad.
Por otra parte, cada unidad deberá mantener un registro que recoja todas las acciones realizadas sobre las bases de datos tanto de gestión como analíticas.
La Oficina Municipal de Datos debe determinar la metainformación de estos sistemas.

=== Gestión de los sistemas de tratamiento de los datos

Las unidades y los entes dependientes deberán poder facilitar, de una forma continuada, la adopción de las nuevas tecnologías y evaluar todo el ciclo de vida de cada sistema de información, con un inventario de las herramientas del software y del hardware asociados al sistema; la gestión y la sostenibilidad de los recursos y las infraestructuras que soportan el sistema; deberá determinar activamente las actualizaciones, las revisiones, las sustituciones o las disposiciones que se requieran para llevar a cabo correctamente las funciones de la unidad y proteger sus activos, y deberán asegurar los términos y las condiciones de los contratos y otros acuerdos de servicio que comporten la recogida, el procesamiento, el almacenamiento, el acceso, el intercambio y la disposición de información municipal, que estén confirmados y alineados con la política de protección de datos y que cubran los requisitos legales y éticos de las unidades.

=== Gestión de riesgos

Las unidades deberán valorar las medidas de seguridad de la información y los datos, la gestión de registros, la transparencia, la evaluación de impacto y las cadenas de suministro, y hacerlo durante todo el ciclo de datos, de forma que los riesgos estén evaluados y gestionados.
Además, deberán elaborar un plan en coordinación con el o la DPD, el o la CDO y el CTID para que los sistemas de información estén debidamente protegidos y asegurados y, al mismo tiempo, las acciones de actualización, revisión, sustitución o retirada tengan el máximo nivel de prioridad.footnote:[_Incluye hardware, software o componentes de firmware no mantenidos por sus desarrolladores, vendedores o fabricantes mediante la disponibilidad de parches de software, actualizaciones de firmware, recambios y contratos de mantenimiento_]
También es necesario que periódicamente se revisen y se reporten los riesgos sobre procesos, personas y tecnologías.


=== Plan de resilencia

Las unidades y los entes dependientes municipales deberán elaborar un plan de resiliencia que tenga en cuenta la gestión de sus datos.
El plan de resiliencia es esencial para que los servicios puedan seguir ejerciendo sus tareas en situaciones de disrupción.
Por lo tanto, es necesario que las entidades desarrollen estrategias de continuidad para asegurar que los servicios se puedan restablecer a tiempo para alcanzar sus objetivos.
Los “atajos manuales” deben formar parte de ello, para que las operaciones críticas puedan tener continuidad mientras no se restablecen los servicios normales.

== La infraestructura de datos de la ciudad (_City Data Infrastructure_)

Esta línea de acción quiere fijar las bases en el nivel arquitectónico para permitir agilizar la gestión interna del Ayuntamiento, mejorar el servicio que el Ayuntamiento ofrece a la ciudadanía y facilitar el intercambio conjunto de datos interesantes tanto dentro del Consistorio como fuera, con la sociedad, y asegurar su preservación y acceso continuado.
El o la CDO y su Oficina serán responsables de entender los datos del Ayuntamiento y de tener una visión unificada y documentada de ellos, así como de mantener, planificar y hacer evolucionar su arquitectura acercándose a un modelo unificado de gestión.

Así, el Ayuntamiento debe avanzar hacia un modelo de datos agrupados desde fuentes diferentes para crear repositorios comunes de datos con finalidades de gestión y analítica, y de preservación segura.
Estos repositorios son:

* *_Data lake_*. Se crea un repositorio analítico único, un lago de datos, en el cual los puntos de ingesta y de consumo o acceso de los datos estén centralizados.
Estos puntos únicos de ingesta o de acceso permitirán fortalecer la seguridad y tener una mejor trazabilidad.
Además, el data lake, que debe estar basado en una infraestructura de tipo big data, debe permitir disponer de un mapa preciso de los datos del Ayuntamiento.
Eso implica que el o la CDO debe priorizar los posibles desarrollos o definiciones de data sets, o conjuntos de datos, y los derechos de acceso y explotación de los datos que se incluyen o se excluyen del data lake.
También será responsable de asegurar la calidad de los datos.
Este data lake es el emblemático proyecto actual City OS.

image::CityOS_infograph_{lang}.svg[Infografia CityOS, , width=2446]

_City OS es un proyecto de depósito y arquitectura transversal para el almacenamiento y el acceso centralizado y uniforme a los datos de la ciudad.
Es el repositorio analítico único de los datos municipales.
El conjunto de datos municipales está almacenado en sistemas diversos según las necesidades de uso y la tecnología que se haya aplicado.
City OS permite disponer de una capa analítica para todos los datos.
Se ha desarrollado de manera que permite gestionar el conocimiento de los diferentes datos municipales de forma autónoma a los sistemas de datos de gestión operativa.
Es decir, independiza los análisis de los datos y la gestión operativa.
Los datos están organizados según un sistema de ontologías orientado a crear conocimiento analítico._

* *Repositorio municipal seguro verificado*: Este repositorio de preservación archivística deberá garantizar el acceso continuado a todos los datos, los registros o los recursos de información municipales que, después de unos procesos de evaluación archivísticos, hayan sido seleccionados para una preservación permanente.
El repositorio seguro debe garantizar la autenticidad de los datos almacenados y evitar la obsolescencia de los materiales digitales, pero permitiendo la sostenibilidad de esta herramienta a largo plazo.

Será necesario escribir una política de información que contemple todos los datos y sus procesos obligatorios para llevar a cabo el ciclo de vida y poder llevarlos hacia el _city lake_ o hacia el repositorio seguro de preservación, según se quiera.
Para hacerlo, hará falta la colaboración estrecha tanto del IMI (proveedor de tecnología y responsable del desarrollo y el mantenimiento de la infraestructura tecnológica del Ayuntamiento) como de las diferentes unidades y servicios que tienen infraestructuras propias.

Es necesario que las unidades elaboren un documento de arquitectura (DA) que describa la arquitectura disponible, la arquitectura objetivo y el plan para alcanzar esta última.
El DA de cada unidad se debe alinear con el *modelo de datos* definido por la OMD.
El DA debe incluir los planes de la unidad para cambios significativos de actualizaciones, revisiones, sustituciones o disposición de información cuando los sistemas ya no soporten de manera efectiva las necesidades y las funciones requeridas.
El DA debe alinear los recursos operacionales y tecnológicos para alcanzar los objetivos estratégicos.
El proceso de descripción del estado presente y futuro de la unidad ayuda a eliminar duplicados y datos no relevantes, incrementa los servicios compartidos, maximiza el rendimiento y promueve la interrelación entre las áreas.
El DA debe identificar las funciones que es necesario que tengan acceso a sistemas determinados y también qué perfiles pueden tener acceso a qué información y bajo qué circunstancias.
Se deben definir los requerimientos basados en atributos para acceder a información sensible y se deben reportar en los sistemas de registro (_logging_).

En el ámbito del proyecto emblemático de City OS, se llevarán a cabo diferentes subproyectos, como por ejemplo:

* *Mejoras del API de ODI.* Mejora del por tal del Open Data BCN (ODI) de Barcelona para centrarlo en la reutilización y en las personas desarrolladoras; añadir capacitados de registro de APP, control de acceso, boletín de noticias y mejorar la documentación del API para que sea fácil de utilizar por personas desarrolladoras.
* *IGLU.* Convergencia de diferentes conjuntos de datos en una solución de almacenamiento unificado (lago de datos) a través de la estandarización y la transformación API del proyecto City OS; aprovechando nuevas ofertas de infraestructuras clave, adaptarlas a un nuevo estándar unificado de operabilidad.
* *API standardization.* Definición y puesta en práctica de estándares para la guía de compra de tecnología para asegurar la interoperabilidad de los proveedores de datos del Ayuntamiento.
* *Protocolos para abrir los datos abiertos.* Definición del protocolo que se debe seguir para incluir datos de manera proactiva al catálogo de datos abiertos, en particular para funcionarios y funcionarias de la ciudad dispuestos a hacerlo.
* *Conexión con la infraestructura DECODE:* Conexión de City OS, IRIS, ASIA, SENTILO
i	BCNOpenData en la plataforma experimental DECODE. (_https://decodeproject.eu/_)

== Innovación interna basada en los datos: analítica y proyectos basados en datos


La importancia de los datos en la Administración no para de crecer.
Se debe diseñar una estrategia que perdure en el tiempo para llevar a cabo proyectos del Ayuntamiento basados en una explotación innovadora de los datos, realizar una mejora analítica y utilizar metodologías de _big data_ para no quedarnos atrás con respecto a la sociedad y el sector privado.
En este sentido, es bueno aprender de experiencias avanzadas en este ámbito, de las cuales los Estados Unidos son un buen ejemplo. footnote:[_Por ejemplo, ver el documento https://ash.harvard.edu/links/lessons-leading-cdos-framework-better-ci-vic-analytics, mayo del 2017._]
//enlace roto

Las organizaciones modernas se caracterizan por la necesidad de gestionar sus servicios y procesos, fundamentados en un conjunto de bases de datos que se han multiplicado en los últimos años y que no dejarán de crecer en un futuro próximo.
La gestión eficiente, coordinada y estructurada de los datos contribuye a diferentes objetivos en una organización como el Ayuntamiento de Barcelona. Más allá de las finalidades específicas e instrumentales de cada base de datos, la gobernanza global debe permitir dos objetivos irrenunciables en una organización pública moderna:

* *La gestión con conocimiento*: se trata de diseñar e implementar proyectos y servicios basados en datos (_data driven_) haciendo un uso intensivo de los datos, de metodologías de analítica de datos y de la data science o ciencia de datos, para adaptar los servicios a las necesidades reales de la ciudadanía, responder a problemas reales, identificar y gestionar riesgos reales y reducir errores.

* *El empoderamiento ciudadano*: se trata de devolver a la ciudadanía el control de sus datos mediante herramientas y procesos municipales, dándole la posibilidad de decidir sobre los usos que se hacen de sus datos y para qué propósitos; y de ofrecer servicios y proyectos que empoderan a la ciudadanía y le otorgan más control sobre la actuación de la ciudad.

Las necesidades de creación de conocimiento e inteligencia del Ayuntamiento de Barcelona han sido y siguen siendo estratégicas.
En los últimos años, el volumen de información se ha multiplicado exponencialmente (big data).
Pero las herramientas analíticas corporativas no pueden dar respuesta al manejo razonable de este volumen de información; la información disponible se encuentra dispersa (mayoritariamente en hojas de cálculo), inconexa y sujeta a un mantenimiento no programado.
Delante de este “agujero”, se han emprendido diferentes iniciativas para crear una plataforma y una cultura de datos accesibles y centralizados y la cultura correspondiente para alimentar y, próximamente, utilizar los datos de la plataforma: en particular el City OS, el proyecto de depósito de información corporativa centralizada que debe permitir la obtención, la preparación, la organización y el análisis de los datos a los servicios municipales y a la ciudadanía en general para fomentar estos proyectos basados en datos a través del Ayuntamiento y también fuera (ver la siguiente sección sobre _open data_)

La nueva cultura de los datos debe permitir el flujo de la información y del conocimiento a través de la organización de una forma mucho más eficiente.
Sin embargo, en el mundo actual no es suficiente con obtener y analizar los datos en procesos _post mortem_.
Se requiere la capacidad de analizar los datos en tiempo real y poder elaborar proyecciones y escenarios mediante algoritmos complejos para prever y predecir posibles situaciones futuras y reducir las repercusiones no deseadas.
Esta capacidad no se puede subrogar, sino que debe estar interiorizada en la organización, ya que es una parte importante de su materia gris. Hasta ahora, los proyectos de servicios digitales han sido liderados desde sectores ajenos a la analítica de datos o la data science (informática, gestores de aplicaciones transaccionales, etcétera).
Para asegurar el buen funcionamiento del modelo de gestión de análisis de datos, hay que transitar entre el paradigma pasado de la inteligencia de negocio, basada en la selección y la visualización de datos, y un nuevo modelo de ciencia de datos del cual resulten análisis predictivos, análisis prescriptivos o la inteligencia artificial.
Desde esta perspectiva, la OMD debe tener un papel relevante en los elementos clave de la definición y la gestión de los datos, como el modelado, el acceso, la metainformación, la calidad o el ciclo de vida.

La analítica debe responder un máximo de preguntas en relación con diferentes ejes:

* Ciudadanía: la mejora de la satisfacción de la ciudadanía con la gestión municipal, la racionalización de procesos, el aumento de la eficiencia, la adaptación a las nuevas necesidades.
* Gestión interna: integración de la analítica en las aplicaciones y los indicadores.
* Gestión del riesgo: enriquecimiento de servicios con analítica avanzada.
* Difusión: la aportación de más valor y calidad a los productos analíticos al servicio de la comunidad como los _open data_ o la estadística.

En esta línea, la *OMD* tiene la misión de cambiar la cultura interna de la organización con respecto a la gestión de datos en sus proyectos.
Dado que los datos y la tecnología asociada a esta disciplina son bastantes nuevos, la OMD ha de proporcionar servicios analíticos de consultoría y de soluciones basadas en datos al resto de unidades.
Estos servicios deben ir acompañados de una formación adecuada para capacitar progresivamente cada unidad del Ayuntamiento para que entienda la metodología del enfoque cualitativo de los problemas de la ciudad basado en los datos.
También debe liderar una transformación interna para “evangelizar” a la organización en la cultura del hecho (datos), a través de talleres y seminarios internos.
Dentro de la OMD, se debe crear un *área de analítica* que ofrecerá servicios internos en diferentes áreas del Ayuntamiento en forma de “consultoría interna”, con una parte dedicada a la resolución de problemas y también a la formación de personas internas de cada departamento sobre cómo utilizar las herramientas desarrolladas.

La OMD y el área de analítica, como elementos integradores de la analítica, también han de colaborar para establecer la visión y la estrategia de todas las iniciativas orientadas a los datos de la corporación, el intercambio de conocimiento sobre políticas, estándares y buenas prácticas de administración de los datos, o la alineación de las herramientas tecnológicas a las necesidades de uso.

Los proyectos emblemáticos en este eje son los siguientes:

* *Sistema de Información Integral de los Espacios y de las Actividades Económicas de Barcelona (EIAE)*: creación de una base de datos corporativa de referencia para el análisis estratégico en el ámbito del desarrollo económico local.

* *Monitorización de la gentrificación*: aportación de información y datos para definir respuestas para detener los procesos de expulsión de vecinos y vecinas y de comerciantes de los barrios de la ciudad.

* *Cuadro de Mando de la Gerencia Municipal*: herramienta de visualización de datos que explica el estado de la ciudad en tiempo real.

* *Observatorio Metropolitano de la Vivienda de Barcelona (OHB)*: el Ayuntamiento de Barcelona, el Área Metropolitana de Barcelona, la Diputación de Barcelona y la Generalitat de Catalunya han creado un instrumento de ámbito supramunicipal para analizar y consultar los datos relacionados con la vivienda.
Se presenta como la herramienta de referencia para la ciudadanía y las administraciones en cuestiones relativas a la vivienda, una herramienta para evaluar y diseñar las políticas de vivienda y analizar y consultar los datos disponibles sobre esta materia.

== Barcelona Data Exchange: la valorización externa de los datos

El Ayuntamiento de Barcelona recoge y publica regularmente un conjunto importante de datos, estadísticas, indicadores y estudios sectoriales sobre la ciudad y su entorno con el objetivo que responsables urbanos, personas del ámbito de la investigación, la consultoría y el emprendimiento, o la ciudadanía en general, puedan tener un conocimiento preciso sobre la ciudad, las dinámicas sociodemográficas, la economía, el espacio urbano, el estado de opinión de la ciudadanía sobre materias diversas, etcétera.

El objetivo de esta línea de trabajo es crear el BCN Data Exchange, un elemento esencial del *_data commons_*, y organizar, centralizar y mejorar los formatos, la reusabilidad (mediante la interoperabilidad) y el acceso de estos datos publicados por el Ayuntamiento, tanto desde la perspectiva técnica (basada en el City OS), como relacional, y establecer contactos con los grupos de personas usuarias y reusuarias (_reusers_) de datos de Barcelona e intentar mostrar nuestra visión de los datos como bien público que se debe compartir bajo unas reglas claras y transparentes.

El proyecto de BCN Data Exchange quiere conectar la ciudad con las personas más interesadas en los datos (stakeholders), comprender su percepción de los datos e intentar construir un marco que anime al uso responsable de los datos y que se ve como un proveedor para construir soluciones y servicios y no como un bien propietario que ofrece una ventaja.
Además, la ciudad escuchará sus aportaciones sobre cuestiones relacionadas con las ofertas públicas y las prácticas de intercambio de datos.


Esta línea contiene tareas dedicadas a preparar y publicar los datos de la ciudad, con la infraestructura necesaria para hacerlo, y a involucrar una comunidad de personas usuarias profesionales y consumidoras proactivas (_prosumers_) de datos en un diálogo constructivo, que abarca el conjunto de datos y la apertura de infraestructuras.

Actualmente, de esta información —que incluye datos de naturaleza y formato diversos (datos sin tratar, indicadores, tablas estadísticas, estudios de opinión, encuestas, mapas, análisis sectoriales, etcétera)—, una parte importante se acumula y se publica de forma manual o semiautomática a través de distintos departamentos/webs municipales:

* *Estadística BCN*, que incluye acceso a cerca de 36.000 tablas estadísticas de la ciudad, información por distritos y barrios, el archivo histórico de anuarios estadístico en PDF, así como una aplicación de consulta y generación dinámica de visualizaciones.
El Departamento de Estadística es un departamento del Ayuntamiento de Barcelona especializado en la teoría y la práctica de la recogida de datos y en los análisis y las presentaciones necesarias para convertirlos en información útil.

* *Open Data BCN* nació el año 2010 y el portal se presentó el año 2011 para poner determinados conjuntos de datos a disposición del público como open data o apertura de información del sector público y para permitir su acceso y su reutilización para el bien común y para el beneficio de las personas y las entidades interesadas.
El proyecto Open Data BCN, transversal en diferentes pilares de la estrategia de la ciudad, se basa en los principales estándares y recomendaciones internacionales y adopta algunas características que resumen los principios de este movimiento.

* *BCNROC* (Repositorio Abierto de Conocimiento) es el repositorio institucional de acceso abierto del Ayuntamiento de Barcelona, mediante el cual el Ayuntamiento ofrece acceso libre y gratuito a sus documentos digitales de difusión pública.
BCNROC es un sistema de búsqueda avanzado, con una tecnología de búsqueda moderna, que incluye metadatos descriptivos extensos para asegurar a la persona usuaria una buena experiencia de búsqueda y la reutilización de la información.
BCNROC elimina las barreras económicas, tecnológicas y jurídicas para acceder a la documentación digital municipal y tiene la voluntad de garantizar el acceso permanente a estos ficheros digitales.
Es la herramienta que permite recoger, almacenar, gestionar, compartir, transformar y difundir los recursos de información de autoría municipal y sus metadatos, y facilitar las búsquedas y su posterior recuperación, acceso y reutilización.

* *CBAB* es el catálogo de las bibliotecas del Ayuntamiento de Barcelona que recoge los metadatos descriptivos de los recursos de información internos y externos que el Ayuntamiento de Barcelona necesita para su tarea diaria, y ofrece un enlace directo a los recursos disponibles en línea, los cuales están a disposición de la corporación y también de toda la ciudadanía, que puede consultarlos directamente o pedirlos en préstamo a través del SEDAC.

* *Barcelona Economía* es el sitio web del Ayuntamiento de Barcelona donde se hace el seguimiento de la economía de la ciudad a partir de una recopilación y de una valoración del comportamiento de los indicadores principales de coyuntura de Barcelona y de su entorno metropolitano.
Barcelona Economía incluye numerosas tablas y gráficos, esencialmente económicos, agrupados por subtemas y que suelen ir acompañados de un breve análisis, así como documentos en PDF sobre coyuntura económica, publicaciones históricas, etcétera.

* El *Registro de encuestas y estudios de opinión* incluye los trabajos demoscópicos encargados por el Ayuntamiento sobre valoración de servicios, usos del tiempo, movilidad, consumos culturales, etcétera.
Algunos de los resultados ya están incorporados en formato de tabla en el portal de estadísticas, mientras que otros están en formato documento.

* El *Geoportal* y los servicios web de la infraestructura de datos espaciales del Ayuntamiento de Barcelona permiten poner al alcance del público la información territorial municipal a través del web, utilizando los estándares del Open Geospatial Consortium (OGC).
La necesidad de crear una infraestructura de geoservicios se fundamenta en una demanda tanto de gestión interna como externa en el ámbito de la interoperabilidad de la información territorial.

* *CartoBCN*: es el web de descargas de cartografía del Ayuntamiento de Barcelona destinado a personas usuarias finales, un proyecto de la Dirección de Información de Base y Cartografía que tiene el objetivo de convertirse en el centro de producción cartográfica del Ayuntamiento de Barcelona.

Con el objetivo de facilitar y potenciar el uso de toda esta información y conocimiento acumulado, el Ayuntamiento de Barcelona se propone diseñar y poner en marcha *un nuevo portal de consulta y exploración de información*, asentado sobre el City OS, que centralice en un solo web el conjunto de información y documentos gestionados y publicados actualmente, es decir, crear el *Barcelona Data Exchange*, con distintos objetivos:

* Centralizar, en un único entorno web, el conjunto de información y documentos gestionados y publicados actualmente.
* Ofrecer una nueva experiencia de consulta más dinámica, interactiva y gráfica donde la persona usuaria pueda explorar rápidamente el amplio conjunto de información disponible.
* Añadir nuevas funcionalidades para consumir, compartir y difundir información relevante de Barcelona pensando en los diferentes perfiles usuarios: ciudadanía, estudiantes, personal técnico o investigador, etcétera.
* Abrir un nuevo entorno para explorar y consultar información de una forma más libre, directa y amigable.
* •	Ofrecer una forma nueva de presentar la información: más gráfica, más interactiva y con más capacidad de compartirla.
* Tener una arquitectura de datos nueva: conectada al City OS del Ayuntamiento, que permita explorar y mostrar contenidos de naturaleza diversa (datos con formatos diferentes para una explotación posterior, documentos en PDF, páginas y posts en HTML, etcétera) y que tenga más facilidad de administración y gestión de contenidos.

Este nuevo portal de datos de Barcelona irá dirigido a personas usuarias de perfiles y necesidades diferentes: desde personal responsable político y técnico municipal que necesita tener acceso a información clave y completa sobre dinámicas que afectan a su toma de decisiones, hasta el ciudadano o ciudadana normal que busca algún dato concreto o que puede tener curiosidad por alguna información o indicador urbano.
Eso implica controlar la seguridad aplicando los diferentes perfiles y funciones.
En medio, hay personas de ámbitos como la investigación o el periodismo o estudiantes, que tienen necesidades diferentes con respecto a la tipologia, la cantidad y el grado de detalle de las informaciones de la ciudad.

Con respecto a los proyectos actuales de repositorios y webs de datos de la ciudad, el Barcelona Data Exchange permitirá mejorar el acceso a la información y el cumplimiento de los principios FAIR para datos abiertos científicos con datos interoperables y con formatos estándares:

* Mejorará el acceso y la interoperabilidad de los datos de la estadística municipal sobre la ciudad como sistema y su realidad socioeconómica, demográfica y urbanística, con un conjunto de datos estadísticos fiable, eficiente y actualizado, y, ahora, interoperable y estándar.

* Como elemento central de la estrategia de datos de “Barcelona ciudad digital”, la mejora de las funcionalidades de Open Data BCN fomentará una economía digital plural con un modelo nuevo de innovación urbana basado en la transformación y la innovación digital del sector público y la implicación entre las empresas, las administraciones, el mundo académico, las organizaciones, las comunidades y las personas, con un liderazgo público y ciudadano claro.

* La documentación municipal actual de BCNROC ya sirve de repositorio único al cual apuntan las otras webs municipales que difunden documentación municipal, y ahora se incorporará al Barcelona Data Exchange.
Su información es interoperable con otros repositorios de acceso abierto nacionales e internacionales, porque soporta los estándares y protocolos OAIPMH (_Open Archives Initiative Protocol for Metadata Harvesting_), permite la reutilización de la documentación empleando las licencias Creative Commons más abiertas posibles y cumple con los estándares de metadatos Dublin Core para contribuir a facilitar la web semántica.
Estos principios se extenderán al resto de conjuntos de datos, cuyos gestores podrán aprovechar la experiencia y la competencia de los responsables de BCNROC.

* De la misma forma, los datos de Barcelona Economía serán más utilizables, y se pondrá a la disposición del público el registro continuado de indicadores en un conjunto ordenado de datos seriados, pero también la información y la valoración de los cambios metodológicos hechos para obtenerlos y que son relevantes para interpretar su evolución temporal.

En este sentido, las iniciativas para la publicación y la valorización “externa” de datos contempla acciones como:

* Utilizar y vincular las iniciativas científicas de datos (data science) existentes bajo el paraguas del Ayuntamiento, para generar un espacio en el portal Open Data BCN en el cual los científicos seleccionados podrán aportar datos y también mantenerlo.
* Utilizar del programa "NUMA DataCity" para establecer desafíos para resolver los problemas de la ciudad y promover el posicionamiento consciente de los objetivos del programa de datos comunes para empresarios y empresas emergentes.
* *Opening WiFi Data:* un servicio API para dar acceso a los datos de Barcelona WiFi y cumplir igualmente las obligaciones de privacidad.
* *Opening Sentilo Data:* se hará accesible para un público más amplio, con un protocolo y API para el acceso oficial a Sentilo para realizar consultas, y una documentación adecuada de todos los conjuntos de datos presentes en la plataforma.

Los proyectos emblemáticos de este eje son los siguientes:

* *BCN Data Store:* será la biblioteca pública de servicios, fácil de usar y escalable a medida que se desarrollen los servicios ofrecidos por la Oficina Municipal de Datos.
* *BCNOpenData:* las mejoras en las funcionalidades de BCNOpenData permiten el acceso y la reutilización, para el bien común y para el beneficio de personas y entidades interesadas, de los datos generados o custodiados por los organismos públicos.
* *Data City Challenges:* procurando tener la mejor eficiencia en los servicios que presta el Ayuntamiento, utilizaremos conjuntos de datos y la ciudad como modelo de experimentación para buscar soluciones a los principales retos urbanos.
