ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Gobernanza de los datos municipales: la Oficina Municipal de Datos

Esta *Estrategia del uso responsable y ético de datos* implica un cambio organizativo que debe permitir la aplicación correcta de las disposiciones que la incluyen.

== Organización: la Oficina Municipal de Datos

Se crea la *Oficina Municipal de Datos* (OMD), una dirección que integra diferentes direcciones y departamentos que hasta ahora tenían misiones sobre datos corporativos.
La Oficina Municipal de Datos está ubicada en la Gerencia Municipal y responde a la Comisionada de Tecnología e Innovación Digital (CTID).

La OMD es responsable de la gestión, la calidad, la gobernanza y la explotación de los datos relacionados con el Ayuntamiento de Barcelona y todos sus entes asociados (públicos o privados) que den servicio a la ciudadanía.
El director o directora de la OMD (_chief data officer_, CDO) llevará a cabo esta tarea mediante:

* La promoción, la ejecución y la supervisión de los proyectos de explotación de datos necesarios para los departamentos del Ayuntamiento.
También interpelará actores relevantes de la ciudad en el sector de los datos.
Para realizar esta tarea, contará con una oficina de apoyo multidisciplinar.

* El establecimiento de protocolos estandarizados en toda la organización y un mapeo preciso de toda la riqueza de datos existentes bajo el paraguas del Ayuntamiento, con la creación de una clasificación de todos los datos y el impulso a políticas de tratamiento, cuidado y preservación adecuadas para cada una.

* Asimismo, su oficina velará por una gestión responsable de los datos de acuerdo con las leyes vigentes en materia de privacidad a través de la coordinación con el delegado o delegada de protección de datos (DPD) y supervisará la integración, en la estructura municipal, de los datos generados en nuevos contratos y servicios.

* Gestión y seguimiento de la gobernanza de datos corporativa.

La Oficina Municipal de Datos es una oportunidad para destacar, en los niveles municipal, nacional, estatal y europeo, en el ámbito de los datos y coincide en un buen momento en el tiempo.
Se trata, claramente, de una apuesta de futuro y presente, ya que los datos invaden a todos y cada uno de los ámbitos de nuestra vida y, en un futuro muy próximo, cada uno de los servicios municipales será susceptible de generarlos, por lo que tenemos que estar preparados y preparadas, como organización, y tener una estrategia sólida sobre cómo gestionarlos y, si es necesario, explotarlos para mejorar el servicio prestado a la ciudadanía.

Por la naturaleza de sus actividades, la Oficina tiene que estar dotada de un equipo interdisciplinario y coherente.
Normalmente, los perfiles que se deberán buscar (desde la Oficina o en contacto con otras unidades del Ayuntamiento) serán de tipo administrativo (gobernanza de datos, pliegos), legal (aspectos de privacidad y licencias), técnico de diversas disciplinas (será necesario un conocimiento de la arquitectura de datos existente y de las acciones necesarias durante su ciclo de vida para transformarlos en un activo, así como de los procedimientos técnicos para garantizar el uso FAIR de los datos), analítico (uno de los objetivos últimos de la Oficina es hacer ciencia de datos), gráfico (habrá una necesidad constante de comunicar el conocimiento extraído de los datos mediante visualizaciones) y finalmente con visión de negocio (la Oficina deberá proveer servicio a diferentes unidades del Ayuntamiento).

Asimismo, el impulso a la gestión del cambio será uno de los otros objetivos de la Oficina con el fin de transformar la cultura de la organización, promover la estandarización de protocolos de gestión de datos e incitar a los diferentes actores municipales a compartir datos y a recibir formación en este aspecto.
Esto requiere un apoyo político decidido, que dote de recursos y autoridad a la nueva oficina para llevar a cabo las ambiciosas tareas que tiene encomendadas.

Más allá del apoyo político, para conseguir este objetivo, la Oficina del o de la CDO debe ser considerada por las otras unidades del Ayuntamiento como un proveedor de servicios.
Esto implica que la Oficina debe proporcionar información útil y trabajar de lado con las otras unidades para educarlas en la cultura de los datos y animarlas a continuar por su cuenta una vez terminen la colaboración.
Por eso, se debe ubicar en un sitio adecuado y con dependencias adecuadas.

En la *Instrucción* que acompaña esta medida, se establecen las funciones y responsabilidades principales de la OMD.

== Supervisión: Comisionado para la Tecnología y la Innovación Digital (CTID)

El CTID debe formar parte de las mesas de gobernanza que informen de decisiones que incluyan recursos de TI y datos, para poder facilitar información avanzada de los recursos con los objetivos de los programas.
El CTID, en consulta con otras gerencias, podrá delegar sus funciones en otro personal técnico.

El CTID requiere que la seguridad y la privacidad de los datos estén completamente integradas en el sistema de medidas de uso y evaluación de los datos a escala municipal, y puede recomendar a las gerencias de las entidades que modifiquen, detengan o finalicen cualquier compra, inversión o actividad que incluya componentes de TI significativos, basándose en las evaluaciones del CTID dentro de los términos de los contratos y de la legislación vigentes.

Se establecerá un proceso que, de forma regular, coordinará el CTID con las personas gestoras de los proyectos para evaluar los recursos de TI y los procesos de gestión de datos que dan apoyo a las finalidades y la misión de cada entidad municipal.
Es necesario que el CTID y las personas responsables del programa compartan la responsabilidad de asegurar que los recursos de TI y los conjuntos de datos municipales presentes y futuros proporcionan adecuadamente el valor que aplican a las gerencias y a los entes municipales.

Las gerencias y los entes municipales deberán cumplir los reglamentos y las instrucciones de la OMD con respecto a la gestión de datos, de la información y de los documentos municipales que se deriven desde los órganos ejecutivos, y que se desarrollarán a partir de esta estrategia de gestión responsable de datos liderada por la Comisionada de Tecnología e Innovación Digital.
