ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Proyectos emblemáticos

El programa relativo a la aplicación de una nueva estrategia que hace valer los datos para la toma de decisiones, descrito en los apartados anteriores, se despliega por toda la organización, de forma transversal y multidisciplinaria, mediante la puesta en marcha de un conjunto de proyectos.

Estos proyectos tienen como eje vertebrador la creación de la Oficina Municipal de Datos y el desarrollo de una nueva arquitectura, donde la puesta en marcha del nuevo diseño de repositorio de datos tipo data lake debe servir para sustentar toda la estrategia de datos que se debe desplegar mediante los proyectos que se describen a continuación, así como todos los otros que se planteen en el futuro.

En esta sección presentamos los proyectos más relevantes que se llevarán a cabo, algunos de los cuales ya se encuentran en fase avanzada, en relación con este programa de datos, y que por su contenido y su relevancia denominamos “proyectos emblemáticos”, de los cuales hacemos una breve descripción.

|===
| 1. Oficina Municipal de Datos | 2. City OS
| 3. Open Data BCN | 4. DECODE
| 5. Data City Challenge | 6. Data Exchange
| 7. Cuadro de Mando de la Gerencia Municipal | 8. Monitorización de la gentrificación
| 9. Censo de Actividades Económicas | 10. Observatorio de la Vivienda
|===

== Oficina Municipal de Datos

La Oficina Municipal de Datos es una dirección que integra diferentes áreas y departamentos con responsabilidades sobre los datos corporativos, y tiene la responsabilidad de velar por la aplicación de esta medida.
Ubicada en la Gerencia Municipal, responde a la Comisionada de Tecnología e Innovación Digital.
Es responsable de la gestión, la calidad, la gobernanza y la explotación de los datos relacionados con el Ayuntamiento de Barcelona y todos sus entes asociados (públicos o privados) que den servicio a la ciudadanía.

En particular, dentro de la OMD se crea el Departamento de Data Analytics, una oficina de análisis de datos multidisciplinaria que velará por la buena gestión y el respeto de los derechos digitales de la ciudadanía.
Utilizará los datos públicos para proporcionar información que ayude a resolver retos de ciudad, aparte de dar servicio a las distintas unidades municipales.
También tendrá un rol formativo y dinamizador interno para el personal del Ayuntamiento.

== City OS

City OS es una plataforma de analítica avanzada de datos con una visión unificada de la información de la ciudad, basada en productos libres y de código abierto, que se ofrecerá a la comunidad.
Ayudará a detectar problemas a la ciudad, a acortar los tiempos de respuesta y a mejorar los servicios públicos aplicando un análisis descriptivo, predictivo, de simulación y modelado, así como el reconocimiento de patrones.
Las gerencias y direcciones de servicio del Ayuntamiento podrán utilizar esta plataforma de datos para realizar un análisis más esmerado de la información y dictar así mejores políticas públicas que lleguen a la ciudadanía.

== Open Data BCN

El movimiento _open public data_, o apertura de información del sector público, es un movimiento impulsado por las administraciones públicas con el objetivo principal de aprovechar al máximo los recursos públicos disponibles, exponer la información generada o custodiada por los organismos públicos y permitir su acceso y reutilización para el bien común y para el beneficio de las personas y las entidades interesadas.

Open Data BCN, un proyecto que nació el año 2010, ha ido evolucionando para fomentar una economía digital plural y ha desarrollado un nuevo modelo de innovación urbana basado en la transformación y la innovación digital del sector público y la implicación entre las empresas, las administraciones, el mundo académico, las organizaciones, las comunidades y las personas, con un liderazgo público y ciudadano claro.
El proyecto Open Data BCN es transversal en distintos pilares de la estrategia de la ciudad, se basa en los principales estándares y recomendaciones internacionales y adopta algunas características que resumen los principios de este movimiento:

* _Open data_ por defecto
* Calidad y cantidad de la información
* Datos para todos
* Datos para la mejora de la gobernanza
* Promoción de la innovación

== DECODE

DECODE es un proyecto piloto europeo que se desarrolla en Barcelona y Amsterdam para gestionar la soberanía de los datos para la economía compartida.
Las soluciones técnicas que desarrolla este proyecto servirán para ofrecer a la ciudadanía unos servicios mejores y más seguros y, a la vez, para garantizar mejor la propiedad y el control de sus datos.

DECODE explorará cómo construir una economía digital centrada en los datos donde los datos generados y recopilados por la ciudadanía, el internet de las cosas (IoT) y las redes de sensores, estarán disponibles para el bien común (_data commons_), con las protecciones de privacidad adecuadas.

Como resultado, los innovadores, las empresas emergentes, las ONG, las cooperativas y las comunidades locales podrán aprovechar esta información para crear aplicaciones y servicios que respondan a sus necesidades y a las de la comunidad en general.

== Data City Challenge

Continuando con la línea de la maximización de los usos de los recursos (los datos) para mejorar la eficiencia de los servicios que ofrece el Ayuntamiento, los data city challenges utilizarán conjuntos de datos y la ciudad como modelo de experimentación para buscar soluciones a los principales retos urbanos (vivienda, paro, exclusión, salud, energía o movilidad) y desarrollarán prototipos con los actores más capacidades dentro del ecosistema innovador.
Estos proyectos (challenges) nos permitirán hacer pruebas y posteriormente adoptar soluciones claramente definidas y parametrizadas, a la vez que se fomentará la colaboración entre empresas emergentes, otras empresas y el sector público, y se hará valer el uso de los datos para el bien común (_data commons_): mejora de los servicios públicos, fomento de la economía y retorno social del gasto público.

== BCN Data Exchange

El BCN Data Store que desarrollará el Ayuntamiento de Barcelona es un paso más en el camino iniciado con el proyecto BCNOpenData.
Su objetivo es tratar de facilitar el acceso a los datos custodiados por la ciudad, a las personas y a las organizaciones para el bien común (_data commons_).

También desarrollará una filosofía que enfatiza la explotación de los datos de la ciudad en todas las áreas de la actividad política de la ciudad y ayudará a promover una cultura de intercambio clara del “mercado de datos de la ciudad” tanto en el sector público como en el privado.

BCN Data Store será una biblioteca pública de servicios, fácil de usar y escalable a medida que se desarrollen los servicios ofrecidos por la Oficina Municipal de Datos.
Para poder hacerlo realidad, se trabajará bajo el concepto “_platform as a service_” (PaaS).

Integrará comunidades y componentes sociales en todas las entregas y buscará establecer una red de personas y entes socios, miembros, revisores, amigos y seguidores.
Esta estrategia le debe permitir mejorar día a día y mantener un contacto directo con la ciudadanía, así como con profesionales del mundo de la ciencia de los datos (del ámbito de la investigación o la empresa) o estudiantes.

== Cuadro de mando para la gerencia municipal

Además del desarrollo de un cuadro de mando para el equipo de gobierno, se desarrollará una aplicación libre y abierta para la ciudadanía que reflejará los indicadores estratégicos de una forma sintetizada y aportará datos de los servicios del Ayuntamiento con indicadores de gestión de sus proyectos, el grado de cumplimiento de los compromisos del Gobierno, la valoración de la ciudadanía, etcétera.
Este servicio representa un paso importante hacia la transparencia en la gestión municipal y el escrutinio público.

== Monitorización de la gentrificación

El proyecto de monitorización de la gentrificación es un proyecto transversal dentro del Ayuntamiento y tiene como objetivo definir respuestas para detener los procesos de expulsión de vecinos y vecinas y comerciantes de los barrios de la ciudad.
Además, también se quiere diseñar e implantar una estrategia coordinada de medidas y actuaciones que neutralice y revierta los procesos de gentrificación en la ciudad, mediante la defensa del derecho al barrio de la ciudadanía de Barcelona.

Este es un proyecto clave y urgente dentro de las actuales problemáticas de la ciudad y requiere un análisis complejo de datos de distintas áreas, como población, vivienda, actividad económica y turismo.
Nuestra misión en este proyecto será identificar las variables clave de este proceso, describir los vacíos de información y proporcionar un análisis y una diagnosis que sirvan de base para poder establecer nuevas políticas que actúen ante esta problemática.

== Sistema de Información Integral de los Espacios y de las Actividades Económicas de Barcelona, EIAE (Censo de Actividades Económicas)

La Dirección de Comercio del Ayuntamiento de Barcelona impulsa el desarrollo del Sistema de Información Integral de los Espacios y de las Actividades Económicas de Barcelona (EIAE) con el objetivo de dar respuesta a la falta de información integrada de las actividades económicas, así como de los espacios susceptibles de contenerlas, mediante la creación de un sistema de información que integre y normalice los datos sobre las actividades económicas.
Esta base de datos será la referencia corporativa para el análisis estratégico en el ámbito del desarrollo local.
Además, será la base para la construcción de productos y servicios dirigidos, entre otros, al tejido comercial y a la estructura económica local, tanto internamente como para los desarrolladores externos, que son proveedores de servicios dentro de este ámbito.

Conceptualmente, será un nodo abierto dentro de la red de sistemas de información.
Las aplicaciones informáticas y, en especial, el sistema de integración (interoperabilidad interna y externa) se construirán con la nueva metodología de desarrollo ágil y con _software_ libre y abierto.

== Observatorio de la Vivienda

El Observatorio de la Vivienda de Barcelona es un instrumento de ámbito supramunicipal que nace con el objetivo de tener una mirada holística sobre la vivienda para abordar las problemáticas de vivienda en el Área Metropolitana de Barcelona, impulsado por distintas administraciones: el Ayuntamiento de Barcelona, el Área Metropolitana de Barcelona, la Diputación de Barcelona, la Generalitat de Catalunya y la Asociación de Gestores de Vivienda social (GHS).

El conocimiento del sector de la vivienda y la situación residencial de la población desde múltiples vertientes es una necesidad de primer orden y una condición imprescindible para poder diseñar estrategias y políticas públicas juiciosas, rigurosas y eficaces.
Por lo tanto, el Observatorio surge como un instrumento capaz de aportar toda la información y las herramientas necesarias para evaluar y diseñar las políticas que hay que encarar en esta materia y, al mismo tiempo, en la medida que la sociedad ha avanzado en conocimiento y en la exigencia democrática de información, también debe ser un órgano que acerque la información a la ciudadanía.

Por una parte, se quiere contribuir a completar los “agujeros negros” de información y, por la otra, a bajar a unos niveles de detalle territorial que muy a menudo los grandes trabajos estadísticos de amplio espectro no permiten ver.

*Presupuesto y calendario*

A continuación se presenta el calendario de  ejecución de los proyectos emblemáticos relativos a la nueva estrategia de datos municipal.

//falta imatge en castellà.
image::Schedule_{lang}.svg[Schedule]
